apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bits-frontend-svc
  labels:
    app: bits-frontend-svc
spec:
  serviceName: bits-frontend-svc-service 
  replicas: 1
  selector:
    matchLabels:
      app: bits-frontend-svc
  template:
    metadata:
      labels:
        app: bits-frontend-svc
    spec:
      containers:
      - name: bits-frontend-svc
        image: logeshwarann/bits-bank-ui:0586
        env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NEXT_PUBLIC_AUTH_SERVICE
              value: http://bits-auth-svc-service.default.svc.cluster.local:8080
            - name: NEXT_PUBLIC_SITE_URL
              value: http://bits-frontend-svc-service.default.svc.cluster.local:3000
            - name: NEXT_PUBLIC_PLAID_SERVICE
              value: http://bits-plaid-svc-service.default.svc.cluster.local:8090
            - name: PLAID_CLIENT_ID
              value: 67cd296f9771e700234db273
            - name: PLAID_SECRET
              value: 5538302e705630e1b916611500e165
            - name: PLAID_ENV
              value: sandbox
            - name: PLAID_PRODUCTS
              value: frontend,transactions,identity
            - name: COUNTRY_CODE
              value: US,CA
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: bits-frontend-svc-service
spec:
  selector:
    app: bits-frontend-svc
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000