apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-plaid-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-plaid
  template:
    metadata:
      labels:
        app: postgres-plaid
    spec:
      containers:
      - name: postgres-plaid
        image: logeshwarann/postgres-service:bitsbank-bankdb-01
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_PASSWORD
            value: "admin@123"
        volumeMounts:
        - name: postgres-plaid-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-plaid-storage
          persistentVolumeClaim:
            claimName: postgres-plaid-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-plaid-service
spec:
  type: ClusterIP
  selector:
    app: postgres-plaid
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432